### ISSUE TITLE
How to use the bot?

### ISSUE THREAD

**Issue by Quicksy** [evgenyvolferts/cwbot#1]
Что нужно заменить в настройках, чтобы запустить этого бота?
В botctl я так понимаю, скрипт ждёт, что в папке /home будут какие-то управляющие файлы. Какого вида должны быть эти файлы, и что в них должно быть указано?

**Comment by evgenyvolferts** [comment]
Сначала нужно поставить php7, mysql-server, собрать telegram-cli (https://github.com/vysheng/tg)
Затем положить в ~/tg/scripts содержимое папки "telegram-cli & control"
В файлах go.lua, bot.php  указать telegram id администратора и управляющего бота (помидорки)
В файлах service, automate, botctl заменить eugene на пользователя, в профиле которого собирался telegram-cli

Создание ботов через botctl add <amount>
